apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-elasticsearch
  labels:
    component: flow-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      component: flow-elasticsearch
  template:
    metadata:
      labels:
        component: flow-elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.6
        env:
          - name: xpack.security.enabled
            value: "false"
        ports:
          - containerPort: 9200
            name: http
          - containerPort: 9300
            name: transport

